### ISSUE TITLE
is it compatible with sqlx?

### ISSUE THREAD

**Issue by Keda87** [vgarvardt/go-oauth2-pg#17]
I'm planning to use `sqlx` and postgres and I saw that sqlx itself is supported to use pgx driver https://github.com/jackc/pgx/issues/81#issuecomment-95163773

but this library needs a `pgxConn` as the adapter argument

**Comment by vgarvardt** [comment]
This library uses adapter to talk to DB https://github.com/vgarvardt/go-oauth2-pg#postgresql-drivers. And adapter has an implementation for sqlx as well - https://github.com/vgarvardt/go-pg-adapter#postgresql-drivers

**Comment by Keda87** [comment]
thanks for pointing it out
