### ISSUE TITLE
Garbage collection doesn't seem to work

### ISSUE THREAD

**Issue by ekundayo-ab** [vgarvardt/go-oauth2-pg#20]
Hi, got the token store setup as demonstrated in the readme, but the expired tokens are not being deleted. Is there something I need to do?
```.go
// ....
// ....
tokenStore, _ := pg.NewTokenStore(adapter, pg.WithTokenStoreGCInterval(time.Minute))
// ....
// ....
```

It works when the channel connection for the tokenStore sticker is not closed, but when we have this 👇🏾 it doesn't seem to work again 
```.go
tokenStore, _ := pg.NewTokenStore(adapter, pg.WithTokenStoreGCInterval(time.Minute))
defer tokenStore.Close()
// ....

**Comment by ekundayo-ab** [comment]
Never mind, it works

**Comment by ekundayo-ab** [comment]
I think this logic https://github.com/vgarvardt/go-oauth2-pg/blob/943d1f3677bc55968b1465d354f4db1284cc4d1d/token_store.go#L73 should be 👇🏾  as it ensures the ticker go routine channel is closed only when the garbage collection is disabled.
```.go
func (s *TokenStore) Close() error {	
    if s.gcDisabled {		
        s.ticker.Stop()	
    }

    return nil
}
```

Or is it intentional that the garbage collection routine is closed when **it is not disabled** ?

**Comment by ekundayo-ab** [comment]
I think this logic https://github.com/vgarvardt/go-oauth2-pg/blob/943d1f3677bc55968b1465d354f4db1284cc4d1d/token_store.go#L73 
should be 👇🏾  as it ensures the ticker channel is closed only when the garbage collection is disabled.

```.go
func (s *TokenStore) Close() error {	
    if s.gcDisabled && s.ticker != nil {		
        s.ticker.Stop()	
    }

    return nil
}
```

Or is it intentional that the channel is closed when **it is not disabled** ?

**Comment by vgarvardt** [comment]
@ekundayo-ab 

The channel is created only when in is not disabled https://github.com/vgarvardt/go-oauth2-pg/blob/master/token_store.go#L63-L66

So it is being closed with the same condition - only if it is not disabled https://github.com/vgarvardt/go-oauth2-pg/blob/master/token_store.go#L72-L77

**Comment by ekundayo-ab** [comment]
@vgarvardt Ok, so to allow expired tokens to be deleted, I have to remove this line when creating the store ?
```.go
// .......
defer store.Close()
```

**Comment by vgarvardt** [comment]
It depends on where you're initialising and calling this Close. `defer` is called on the exit from the scope, so if you're initialising the store in `main` or a function that is active during the whole app lifecycle - then `defer` will work perfectly file there. But if you're initilising store in a helper function and use `defer` to close it, then th estore will be closed right after initialisation that is not desired behaviour.

This will work fine
```go
func main() {
  store, _ := pg.NewTokenStore(...)
  defer store.Close()
  // the rest of the app
  ...
}
```

This will not work as defer Close will be called right away
```go
func main() {
  store, _ := pg.NewTokenStore(...)
  defer store.Close()
  // the rest of the app
  ...
}

func initStore(...) (*pg.TokenStore, error) {
  store, err := pg.NewTokenStore(...)
  defer store.Close()

  return store, err
}
```

**Comment by ekundayo-ab** [comment]
Ok thanks
