### ISSUE TITLE
Need to make the client store extendable

### ISSUE THREAD

**Issue by nabiel-flik** [vgarvardt/go-oauth2-pg#37]
Currently, this package make it harder to extend because of the SQL query use asterisk instead of selecting the column manually.
<img width="853" alt="image" src="https://github.com/vgarvardt/go-oauth2-pg/assets/144656363/3ac92a8d-123b-48c9-8969-f9f5da9d5922">

and ofcourse because of pg-adapter use sqlx, when I add new columns in the clients table, it returns error because the new columns that I added is not scanned into the struct
<img width="503" alt="image" src="https://github.com/vgarvardt/go-oauth2-pg/assets/144656363/d2d0a404-3d86-4a8b-9562-9be0d67a472d">

So, I think it will be good if we can extend this package easily

**Comment by nabiel-flik** [comment]
Or should we add an option to change the struct for the SQL ? I think if we can do that, it will be more helpful to extending this

**Comment by vgarvardt** [comment]
quick fix is implemented and merged in https://github.com/vgarvardt/go-oauth2-pg/pull/38 - pls check if this is fine for you, then I'll release it

**Comment by nabiel-flik** [comment]
> quick fix is implemented and merged in #38 - pls check if this is fine for you, then I'll release it

I checked this and all is working good now. Really appreciate your work

**Comment by vgarvardt** [comment]
https://github.com/vgarvardt/go-oauth2-pg/releases/tag/v4.4.4
